apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-eta-deploy
  labels:
    app: healthcare-eta-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthcare-eta-app
  template:
    metadata:
      labels:
        app: healthcare-eta-app
    spec:
      containers:
      - name: healthcare-eta-container
        image: waasifahmed/healthcare-eta-app
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-eta-np-service
  labels:
    app: healthcare-eta-app
spec:
  selector:
    app: healthcare-eta-app

  type: NodePort
  ports:
  - nodePort: 31020  
    port: 8081
    targetPort: 8081
